name: ci

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  clippy:
    if: "!contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
          components: clippy
      - uses: actions/checkout@v2
      - name: Clippy
        run: cargo clippy --all-features -- -D warnings

  test:
    if: "!contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable, beta, nightly]
    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
      - uses: actions/checkout@v2
      - name: Run cargo tests
        run: cargo test --all-features --verbose
